### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Alex-LBH** [neil-morrison44/pocket-sync#170]
Hi,
I wanted to install the latest version of pocket sync this morning and I got this error message. Can you help me please.

Pocket Sync: null
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at c4e (https://tauri.localhost/assets/index-210437e8.js:5684:82981)
    at a7 (https://tauri.localhost/assets/index-210437e8.js:38:19538)
    at XI (https://tauri.localhost/assets/index-210437e8.js:40:44069)
    at jI (https://tauri.localhost/assets/index-210437e8.js:40:39801)
    at bW (https://tauri.localhost/assets/index-210437e8.js:40:39729)
    at Yg (https://tauri.localhost/assets/index-210437e8.js:40:39582)
    at L4 (https://tauri.localhost/assets/index-210437e8.js:40:35947)
    at LE (https://tauri.localhost/assets/index-210437e8.js:40:36751)
    at zu (https://tauri.localhost/assets/index-210437e8.js:38:3279)
    at https://tauri.localhost/assets/index-210437e8.js:40:34277

**Describe the bug**
A clear and concise description of what the bug is. Ideally including the error message.

**To Reproduce**
Steps to reproduce the behaviour:

If the error only appeared after installing a certain core or image pack say which one.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 11]

**Additional context**

**Comment by neil-morrison44** [comment]
Can you paste in your `pocket-sync.json` file? Sounds like something’s gone wrong with it.

**Comment by Alex-LBH** [comment]
Here is the content of my pocket-sync.json file. thank you in advance for your help

{
  "version": "3.8.1",
  "notes": "- Improves the UI around not installed cores",
  "pub_date": "2023-09-19T00:40:56.358Z",
  "platforms": {
    "linux-x86_64": {
      "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTS2xBb2NDQXJCN1JIY210YXJHZHJ0NHZMZ2lkdlpuQktVdXRTUDVvT0dsczRxckFaL3AxR1hTTWFoVFArQnU0VnZicnFzLzJVYTREK2dQRlFlUFE4eTZMWjg3VGs2VHdrPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNjk1MDgzNjY4CWZpbGU6cG9ja2V0LXN5bmNfMy44LjFfYW1kNjQuQXBwSW1hZ2UudGFyLmd6ClhzdXlkZjZvM0hKVTRiZWgzbXI3T3NHdVlBQUhZTHBBaCtQaytRNjFiUDRVT2l0S2ErRk5ia0t0eFUzRC9VRnpEM3p0RHNBSUlVSzBJZnFpSDQrN0JRPT0K",
      "url": "https://github.com/neil-morrison44/pocket-sync/releases/download/v3.8.1/pocket-sync_3.8.1_amd64.AppImage.tar.gz"
    },
    "windows-x86_64": {
      "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTS2xBb2NDQXJCN2NOdk1kbG1ZWjZ4bzRhSWEySlJ2WE1QdGtYSllWcUhnWUZHeGhqU24vUnZRcHY1aTkwWS9VdXcySng4OFNLTENmL0hEUm9pcFBLcUsvVmVUYXdwTHdFPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNjk1MDg0MDI4CWZpbGU6UG9ja2V0IFN5bmNfMy44LjFfeDY0X2VuLVVTLm1zaS56aXAKL1VkV0lmdERTa2M4Z1dlZ1B0bW1JSWhoTWp3ZjJ3VFAyL2FnOWNQSFBDSVdoc1pJNUF0aVA0cnZ1UkJVQlduTXJkSEJKUVJTL1pESmdlMFc5bjZBQ0E9PQo=",
      "url": "https://github.com/neil-morrison44/pocket-sync/releases/download/v3.8.1/Pocket.Sync_3.8.1_x64_en-US.msi.zip"
    },
    "darwin-aarch64": {
      "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTS2xBb2NDQXJCN1JSOWhqbjc1bmo4dXFBU1dyVjEwbmEzVFFsWlpuYjJkNm56dnVMVE1XZ1p1Zm5WZjVtc1Ivek9EVzZZVUlCeDJ4UFVzNkkycVUzRTVJTkc4ZkpGSUFjPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNjk1MDg0MDUzCWZpbGU6UG9ja2V0IFN5bmMuYXBwLnRhci5negpidjJoak80NUd6ODNzNFZlVWdpNTBuZENYY1l1MS8rcDVJZEd6ekV0VEl1Z2FMN1BrUWtVM2t1S2lERWpveThWZURSODEyOXQyQ292U1d2cExtQVZCZz09Cg==",
      "url": "https://github.com/neil-morrison44/pocket-sync/releases/download/v3.8.1/Pocket.Sync_universal.app.tar.gz"
    },
    "darwin-x86_64": {
      "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTS2xBb2NDQXJCN1JSOWhqbjc1bmo4dXFBU1dyVjEwbmEzVFFsWlpuYjJkNm56dnVMVE1XZ1p1Zm5WZjVtc1Ivek9EVzZZVUlCeDJ4UFVzNkkycVUzRTVJTkc4ZkpGSUFjPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNjk1MDg0MDUzCWZpbGU6UG9ja2V0IFN5bmMuYXBwLnRhci5negpidjJoak80NUd6ODNzNFZlVWdpNTBuZENYY1l1MS8rcDVJZEd6ekV0VEl1Z2FMN1BrUWtVM2t1S2lERWpveThWZURSODEyOXQyQ292U1d2cExtQVZCZz09Cg==",
      "url": "https://github.com/neil-morrison44/pocket-sync/releases/download/v3.8.1/Pocket.Sync_universal.app.tar.gz"
    }
  }
}

**Comment by neil-morrison44** [comment]
That’s very strange, looks like the wrong file is there - did you put that file there manually?

(Deleting it & restarting the app should fix the issue since it’ll regenerate with the default one unless something’s going very wrong)

**Comment by Alex-LBH** [comment]
I just deleted the pocket-sync file and relaunched the application and it seems to work. Thank you for your help and for the fabulous work you do!

**Comment by neil-morrison44** [comment]
Awesome, would be good to know how that happened if you've got any idea
